"""
Django settings for HowAreYou project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import sys
import django

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^kasj+gxuamafbg(y$nq*9ymccxco-c7w&2nzl&a&p_p)gc+e#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "drf_spectacular",
    "api",
    # "frontend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "HowAreYou.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HowAreYou.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "EXCEPTION_HANDLER": "api.exceptions.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "HowAreYou API",
    "DESCRIPTION": f"""
    Python Version: {sys.version}

    Django Version: {django.get_version()}

    Packages used for application (Refer to requirements.txt):
    asgiref                   3.8.1
    attrs                     24.3.0
    certifi                   2024.12.14
    charset-normalizer        3.4.0
    coreapi                   2.3.3
    coreschema                0.0.4
    coverage                  7.6.9
    Django                    5.1.4
    django-cors-headers       4.6.0
    django-extensions         3.2.3
    django-rest-swagger       2.2.0
    djangorestframework       3.15.2
    drf-spectacular           0.28.0
    idna                      3.10
    inflection                0.5.1
    itypes                    1.2.0
    Jinja2                    3.1.5
    jsonschema                4.23.0
    jsonschema-specifications 2024.10.1
    MarkupSafe                3.0.2
    numpy                     2.2.1
    openapi-codec             1.3.2
    pandas                    2.2.3
    pep8                      1.7.1
    pip                       24.3.1
    python-dateutil           2.9.0.post0
    python-dotenv             1.0.1
    pytz                      2024.2
    PyYAML                    6.0.2
    referencing               0.35.1
    requests                  2.32.3
    rpds-py                   0.22.3
    setuptools                65.5.0
    simplejson                3.19.3
    six                       1.17.0
    sqlparse                  0.5.3
    tzdata                    2024.2
    uritemplate               4.1.1
    urllib3                   2.3.0

    Django Admin username = admin | password = admin123

""",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "url": "/Users/bobby/uol/advanced_web_dev/dev/HowAreYou/schema.yml",
    # OTHER SETTINGS
}
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
