# Generated by Django 5.1.4 on 2024-12-22 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('45dc8291-4b29-41ad-8ebd-05114ba683ed'), primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gte', 12), ('age__lte', 24)), name='Age constraint', violation_error_message='Age must be between 12 (inclusive) and 24 (inclusive)'), models.CheckConstraint(condition=models.Q(('gender', 'M'), ('gender', 'F'), ('gender', 'O'), _connector='OR'), name='Gender constraint', violation_error_message='Gender must be one of {M, F, Q}')],
            },
        ),
    ]
