# Generated by Django 5.1.4 on 2024-12-26 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("2151a167-d47e-4968-8253-2f1e284f6352"),
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
