# Generated by Django 5.1.4 on 2024-12-23 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("6a72f5f1-26b4-4384-a3d8-27e55bde0c36"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
