# Generated by Django 5.1.4 on 2024-12-26 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_resource_url_alter_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("99517c66-d32b-4881-8159-9d401652bda3"),
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
