# Generated by Django 5.1.4 on 2024-12-27 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_resource_url_alter_student_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="Gender constraint",
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female"), ("o", "Others")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("b31feffa-c442-4c08-964f-8e7866b47704"),
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gender", "m"), ("gender", "f"), ("gender", "o"), _connector="OR"
                ),
                name="Gender constraint",
                violation_error_message="Gender must be one of 'M', 'F', 'O'.",
            ),
        ),
    ]
