# Generated by Django 5.1.4 on 2024-12-28 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_student_gender_constraint_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="Gender constraint",
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("f9511d5c-e182-45ae-a39e-385118caea95"),
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gender", "m"), ("gender", "f"), ("gender", "o"), _connector="OR"
                ),
                name="Gender constraint",
                violation_error_message="Gender must be one of 'm', 'f', 'o'.",
            ),
        ),
    ]
