# Generated by Django 5.1.4 on 2024-12-30 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_student_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="created_at",
            new_name="created_at_utc",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="updated_at",
            new_name="updated_at_utc",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="created_at",
            new_name="created_at_utc",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="updated_at",
            new_name="updated_at_utc",
        ),
        migrations.RenameField(
            model_name="studentresponse",
            old_name="created_at",
            new_name="created_at_utc",
        ),
        migrations.RenameField(
            model_name="studentresponse",
            old_name="updated_at",
            new_name="updated_at_utc",
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("251b297f-57ce-44f3-8ad2-895d584060e6"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
